### PR TITLE
Introduce configurable priority threshold for findsecbugs tool

### PR DESCRIPTION
**Pull request by martinavagyan**
Setting name: `findSecBugsPriorityThreshold`
Default value:  `Priority.Normal`   

From the original library documentation this is the description for priority threshold:
_Set the priority threshold. Bug instances must be at least as important as this priority to be reported. Possible values: `High`, `Normal`, `Low`, `Experimental`._

Example in build.sbt:
`findSecBugsPriorityThreshold := Priority.High`

### CODE REVIEW

**Comment by jqno** [comment]
Hi,

Thanks for the PR! That's a useful addition.

However, do you mind if I set the default back to `Low`? That way, the upgrade won't affect existing users. (Maybe the low-priority bugs are important to them, and currently they wouldn't see them anymore, and they wouldn't know about it if they didn't read the changelog very carefully.)

**Comment by martinavagyan** [comment]
Thanks for the reply, that's a valid point. The reason we put it to `Normal` is because the original library uses `Normal` as the default, and the `Low` priority seems to generate some `false positives`.

But to not affect existing users, please set it to `Low`. Would you like me to set it to `Low` ?

**Comment by jqno** [comment]
Thanks! Yes, if you would do that, I'll merge and try to make a release later this afternoon.

**Comment by martinavagyan** [comment]
I have changed `Normal` to `Low`, also have squashed my commits to maintain clean history.

**Comment by jqno** [comment]
Thanks!

**Comment by jqno** [comment]
It's released: version 0.16.

**Pull request merged**
