### PR TITLE
Expose report output path setting

### PR DESCRIPTION
**Pull request by nigredo-tori**
Use case: collecting all the reports to one place in a multi-project build (e.g. to publish them as CI artifacts).

### CODE REVIEW

**Comment by jqno** [comment]
Looks good, but can you show me how this would look in a client `build.sbt`? I don't quite understand the documentation on this one.

**Comment by nigredo-tori** [comment]
@jqno, something like this:
```scala
findSecBugs / artifactPath := (ThisBuild / baseDirectory).value / "target" / "findsecbugs" / (name.value + ".xml")
```
If we have a build with multiple subprojects, and we add this setting to each of them, all the reports will be in the `target/findsecbugs` folder in the build root. This folder can then be exposed as a CI artifact.

As it stands right now, I have to separately expose reports for each subproject.

**Comment by jqno** [comment]
OK. I didn't know you could do `findSecBugs / something := something`. Why not simply `findSecBugsArtifactPath`, analogous to the other settings?

**Comment by nigredo-tori** [comment]
@jqno, https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Reuse+existing+keys

**Comment by jqno** [comment]
Ah, that's a good point.
I'm still a little confused about the syntax though. Can't a user simply write `artifactPath in findSecBugs := (baseDirectory in ThisBuild).value / "target" / "findsecbugs" / (name.value + ".xml")` instead?

**Comment by nigredo-tori** [comment]
@jqno, absolutely, those are equivalent. However, the unified slash syntax seems to be [the preferred way](https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax) to do things in 1.0 - it is used a lot in the documentation. So I tend to use it in the new code, except for projects that have to cross-compile for 0.13.

**Comment by jqno** [comment]
Ah, I wasn't aware of that, thank you!

**Pull request merged**
